-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 12:18:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gd-cip
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gd-cip` ;

-- -----------------------------------------------------
-- Schema gd-cip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gd-cip` DEFAULT CHARACTER SET utf8 ;
USE `gd-cip` ;

-- -----------------------------------------------------
-- Table `gd-cip`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`usuario` (
  `usuId` BIGINT NOT NULL AUTO_INCREMENT,
  `usuContraseña` VARCHAR(45) NULL,
  `usuEmail` VARCHAR(254) NOT NULL,
  `usuNombre` VARCHAR(150) NULL,
  PRIMARY KEY (`usuId`),
  INDEX `usuEmail` (`usuEmail` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`campeonato` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`campeonato` (
  `camId` BIGINT NOT NULL AUTO_INCREMENT,
  `camUsuEmail` VARCHAR(254) NULL,
  PRIMARY KEY (`camId`),
  INDEX `fk_campeonato_administrador_idx` (`camUsuEmail` ASC) VISIBLE,
  CONSTRAINT `fk_campeonato_administrador`
    FOREIGN KEY (`camUsuEmail`)
    REFERENCES `gd-cip`.`usuario` (`usuEmail`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`arbitro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`arbitro` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`arbitro` (
  `arbId` BIGINT NOT NULL AUTO_INCREMENT,
  `arbUsuEmail` VARCHAR(254) NULL,
  `arbNombre` VARCHAR(150) NULL,
  `arbFuncion` VARCHAR(255) NULL,
  PRIMARY KEY (`arbId`),
  INDEX `fk_arbitro_administrador_idx` (`arbUsuEmail` ASC) VISIBLE,
  CONSTRAINT `fk_arbitro_administrador`
    FOREIGN KEY (`arbUsuEmail`)
    REFERENCES `gd-cip`.`usuario` (`usuEmail`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`campeonato_unico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`campeonato_unico` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`campeonato_unico` (
  `camUniId` BIGINT NOT NULL AUTO_INCREMENT,
  `camUniCamId` BIGINT NULL,
  `camUniTitulo` VARCHAR(45) NULL,
  `camUniDescripcion` VARCHAR(255) NULL,
  `camUniFechaInicio` DATE NULL,
  `camUniFechaFin` DATE NULL,
  `camUniTelefono1` VARCHAR(9) NULL,
  `camUniTelefono2` VARCHAR(9) NULL,
  `camUniEmail` VARCHAR(254) NULL,
  `camUniReglas` VARCHAR(255) NULL,
  `camUniPremio1` VARCHAR(45) NULL,
  `camUniPremio2` VARCHAR(45) NULL,
  `camUniPremio3` VARCHAR(45) NULL,
  `camUniPremioOtro` VARCHAR(45) NULL,
  `camUniArbId` BIGINT NULL,
  `camUniOrganizadorNombre` VARCHAR(45) NULL,
  `camUniOrganizadorEmail` VARCHAR(45) NULL,
  `camUniOrganizadorNumero` VARCHAR(9) NULL,
  PRIMARY KEY (`camUniId`),
  INDEX `camUniCamId_idx` (`camUniCamId` ASC) INVISIBLE,
  INDEX `CAMPEONATO_UNICO tiene ARBITRO_idx` (`camUniArbId` ASC) VISIBLE,
  CONSTRAINT `fk_campeonatoUnico_campeonato`
    FOREIGN KEY (`camUniCamId`)
    REFERENCES `gd-cip`.`campeonato` (`camId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `CAMPEONATO_UNICO tiene ARBITRO`
    FOREIGN KEY (`camUniArbId`)
    REFERENCES `gd-cip`.`arbitro` (`arbId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`grupo` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`grupo` (
  `gruId` BIGINT NOT NULL AUTO_INCREMENT,
  `gruCamUniId` BIGINT NULL,
  `gruNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`gruId`),
  INDEX `GRUPO agregado a CAMPEONATO_UNICO_idx` (`gruCamUniId` ASC) VISIBLE,
  CONSTRAINT `GRUPO agregado a CAMPEONATO_UNICO`
    FOREIGN KEY (`gruCamUniId`)
    REFERENCES `gd-cip`.`campeonato_unico` (`camUniId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`equipo` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`equipo` (
  `equId` BIGINT NOT NULL AUTO_INCREMENT,
  `equEmail` VARCHAR(254) NULL,
  `equNombre` VARCHAR(45) NULL,
  `equEntrenador` VARCHAR(150) NULL,
  `equGruId` BIGINT NULL,
  `equCampeonatoId` BIGINT NULL,
  PRIMARY KEY (`equId`),
  INDEX `EQUIPO agregado a GRUPO_idx` (`equGruId` ASC) INVISIBLE,
  INDEX `fk_equipo_administrador_idx` (`equEmail` ASC) VISIBLE,
  INDEX `EQUIPO agregado a CAMPEONATO_idx` (`equCampeonatoId` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_administrador`
    FOREIGN KEY (`equEmail`)
    REFERENCES `gd-cip`.`usuario` (`usuEmail`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `EQUIPO agregado a GRUPO`
    FOREIGN KEY (`equGruId`)
    REFERENCES `gd-cip`.`grupo` (`gruId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `EQUIPO agregado a CAMPEONATO`
    FOREIGN KEY (`equCampeonatoId`)
    REFERENCES `gd-cip`.`campeonato_unico` (`camUniId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`jugador` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`jugador` (
  `jugId` BIGINT NOT NULL AUTO_INCREMENT,
  `jugEmail` VARCHAR(254) NULL,
  `jugNombre` VARCHAR(150) NULL,
  `jugApodo` VARCHAR(45) NULL,
  `jugPosicion` VARCHAR(45) NULL,
  `jugDNI` VARCHAR(8) NULL,
  `jugTelefono` VARCHAR(9) NULL,
  `jugNacimiento` VARCHAR(45) NULL,
  `jugCreacion` VARCHAR(45) NULL,
  `jugEquipoId` BIGINT NULL,
  PRIMARY KEY (`jugId`),
  INDEX `fk_jugador_administrador_idx` (`jugEmail` ASC) VISIBLE,
  INDEX `JUGADOR pertenece EQUIPO_idx` (`jugEquipoId` ASC) VISIBLE,
  CONSTRAINT `fk_jugador_administrador`
    FOREIGN KEY (`jugEmail`)
    REFERENCES `gd-cip`.`usuario` (`usuEmail`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `JUGADOR pertenece EQUIPO`
    FOREIGN KEY (`jugEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`usuario_cip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`usuario_cip` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`usuario_cip` (
  `usuCipCIP` VARCHAR(254) NOT NULL,
  `usuCipNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`usuCipCIP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`campeonatos_seguidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`campeonatos_seguidos` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`campeonatos_seguidos` (
  `camSegUsuEstCIP` VARCHAR(254) NOT NULL,
  `camSegCamId` BIGINT NOT NULL,
  PRIMARY KEY (`camSegUsuEstCIP`, `camSegCamId`),
  INDEX `camSegCamId_idx` (`camSegCamId` ASC) VISIBLE,
  CONSTRAINT `fk_campeonatos_seguidos_usuario_estandar`
    FOREIGN KEY (`camSegUsuEstCIP`)
    REFERENCES `gd-cip`.`usuario_cip` (`usuCipCIP`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campeonatos_seguidos_campeonato`
    FOREIGN KEY (`camSegCamId`)
    REFERENCES `gd-cip`.`campeonato` (`camId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`fases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`fases` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`fases` (
  `idfases` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  PRIMARY KEY (`idfases`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`fase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`fase` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`fase` (
  `fasId` BIGINT NOT NULL AUTO_INCREMENT,
  `fasTipoFase` BIGINT NULL,
  `fasNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`fasId`),
  INDEX `FASE incluye TIPO_FASE_idx` (`fasTipoFase` ASC) VISIBLE,
  CONSTRAINT `FASE incluye TIPO_FASE`
    FOREIGN KEY (`fasTipoFase`)
    REFERENCES `gd-cip`.`fases` (`idfases`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`equipo_jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`equipo_jugador` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`equipo_jugador` (
  `equJugJugId` BIGINT NOT NULL,
  `equJugEquId` BIGINT NOT NULL,
  PRIMARY KEY (`equJugJugId`, `equJugEquId`),
  INDEX `equJugEquId_idx` (`equJugEquId` ASC) VISIBLE,
  CONSTRAINT `fk_equipoJugador_jugador`
    FOREIGN KEY (`equJugJugId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipoJugador_equipo`
    FOREIGN KEY (`equJugEquId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`equipo_campeonato_unico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`equipo_campeonato_unico` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`equipo_campeonato_unico` (
  `equCamEquId` BIGINT NOT NULL,
  `equCamCamUniId` BIGINT NOT NULL,
  PRIMARY KEY (`equCamEquId`, `equCamCamUniId`),
  INDEX `EQUIPO agregado a CAMPEONATO_UNICO_idx` (`equCamCamUniId` ASC) VISIBLE,
  CONSTRAINT `EQUIPO agregado a CAMPEONATO_UNICO`
    FOREIGN KEY (`equCamCamUniId`)
    REFERENCES `gd-cip`.`campeonato_unico` (`camUniId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `CAMPEONATO_UNICO agrega a EQUIPO`
    FOREIGN KEY (`equCamEquId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`fase_campeonato_unico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`fase_campeonato_unico` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`fase_campeonato_unico` (
  `fasCamUniFasId` BIGINT NOT NULL,
  `fasCamUniCamUniId` BIGINT NOT NULL,
  PRIMARY KEY (`fasCamUniFasId`, `fasCamUniCamUniId`),
  INDEX `FASE agregado a CAMPEONATO_UNICO_idx` (`fasCamUniCamUniId` ASC) VISIBLE,
  CONSTRAINT `FASE agregado a CAMPEONATO_UNICO`
    FOREIGN KEY (`fasCamUniCamUniId`)
    REFERENCES `gd-cip`.`campeonato_unico` (`camUniId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `CAMPEONATO_UNICO agrega FASE`
    FOREIGN KEY (`fasCamUniFasId`)
    REFERENCES `gd-cip`.`fase` (`fasId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`partido` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`partido` (
  `parId` BIGINT NOT NULL AUTO_INCREMENT,
  `parFaseId` BIGINT NULL,
  `parEquipoId1` BIGINT NULL,
  `parEquipoId2` BIGINT NULL,
  `parFecha` VARCHAR(45) NULL,
  `parTipoResultado` VARCHAR(45) NULL,
  `parMarcador1` INT NULL,
  `parMarcador2` INT NULL,
  `parMejorJugadorId` BIGINT NULL,
  PRIMARY KEY (`parId`),
  INDEX `PARTIDO agrega EQUIPO_idx` (`parEquipoId1` ASC) INVISIBLE,
  INDEX `PARTIDO agrega EQUIPO 2_idx` (`parEquipoId2` ASC) VISIBLE,
  INDEX `PARTIDO pertenece FASE_idx` (`parFaseId` ASC) VISIBLE,
  INDEX `PARTIDO agrega JUGADOR_idx` (`parMejorJugadorId` ASC) VISIBLE,
  CONSTRAINT `PARTIDO agrega EQUIPO 1`
    FOREIGN KEY (`parEquipoId1`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `PARTIDO agrega EQUIPO 2`
    FOREIGN KEY (`parEquipoId2`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `PARTIDO pertenece FASE`
    FOREIGN KEY (`parFaseId`)
    REFERENCES `gd-cip`.`fase` (`fasId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `PARTIDO agrega JUGADOR`
    FOREIGN KEY (`parMejorJugadorId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`gol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`gol` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`gol` (
  `golId` BIGINT NOT NULL AUTO_INCREMENT,
  `golJugadorId` BIGINT NULL,
  `golAsistenciaId` BIGINT NULL,
  `golDescripcion` VARCHAR(45) NULL,
  `golTiempo` INT NULL,
  `golMinuto` INT NULL,
  `golSegundo` INT NULL,
  `golEnContra` INT NULL,
  `golPartidoId` BIGINT NULL,
  `golEquipoId` BIGINT NULL,
  PRIMARY KEY (`golId`),
  INDEX `GOL incluye JUGADOR_idx` (`golJugadorId` ASC) VISIBLE,
  INDEX `GOL incluido PARTIDO_idx` (`golPartidoId` ASC) VISIBLE,
  INDEX `GOL incluye EQUIPO_idx` (`golEquipoId` ASC) VISIBLE,
  INDEX `GOL incluye JUGADOR 2_idx` (`golAsistenciaId` ASC) VISIBLE,
  CONSTRAINT `GOL incluye JUGADOR 1`
    FOREIGN KEY (`golJugadorId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `GOL incluido PARTIDO`
    FOREIGN KEY (`golPartidoId`)
    REFERENCES `gd-cip`.`partido` (`parId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `GOL incluye EQUIPO`
    FOREIGN KEY (`golEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `GOL incluye JUGADOR 2`
    FOREIGN KEY (`golAsistenciaId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`color` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`color` (
  `colId` BIGINT NOT NULL AUTO_INCREMENT,
  `colNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`colId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`tarjeta` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`tarjeta` (
  `tarId` BIGINT NOT NULL AUTO_INCREMENT,
  `tarJugadorId` BIGINT NULL,
  `tarTiempo` INT NULL,
  `tarMinuto` INT NULL,
  `tarSegundo` INT NULL,
  `tarDescripcion` VARCHAR(45) NULL,
  `tarColorId` BIGINT NULL,
  `tarPartidoId` BIGINT NULL,
  `tarEquipoId` BIGINT NULL,
  PRIMARY KEY (`tarId`),
  INDEX `AMARILLA incluye JUGADOR_idx` (`tarJugadorId` ASC) VISIBLE,
  INDEX `TARJETA incluido PARTIDO_idx` (`tarPartidoId` ASC) VISIBLE,
  INDEX `TARJETA incuye EQUIPO_idx` (`tarEquipoId` ASC) VISIBLE,
  INDEX `TARJET incluye COLOR_idx` (`tarColorId` ASC) VISIBLE,
  CONSTRAINT `AMARILLA incluye JUGADOR`
    FOREIGN KEY (`tarJugadorId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `TARJETA incluido PARTIDO`
    FOREIGN KEY (`tarPartidoId`)
    REFERENCES `gd-cip`.`partido` (`parId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `TARJETA incuye EQUIPO`
    FOREIGN KEY (`tarEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `TARJET incluye COLOR`
    FOREIGN KEY (`tarColorId`)
    REFERENCES `gd-cip`.`color` (`colId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`falta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`falta` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`falta` (
  `falId` BIGINT NOT NULL AUTO_INCREMENT,
  `falJugadorId` BIGINT NULL,
  `falTiempo` INT NULL,
  `falMinuto` INT NULL,
  `falSegundo` INT NULL,
  `falPartidoId` BIGINT NULL,
  `falEquipoId` BIGINT NULL,
  PRIMARY KEY (`falId`),
  INDEX `FALTA incluye JUGADOR_idx` (`falJugadorId` ASC) VISIBLE,
  INDEX `FALTA incluye PARTIDO_idx` (`falPartidoId` ASC) VISIBLE,
  INDEX `FALTA incluye EQUIPO_idx` (`falEquipoId` ASC) VISIBLE,
  CONSTRAINT `FALTA incluye JUGADOR`
    FOREIGN KEY (`falJugadorId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `FALTA incluye PARTIDO`
    FOREIGN KEY (`falPartidoId`)
    REFERENCES `gd-cip`.`partido` (`parId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `FALTA incluye EQUIPO`
    FOREIGN KEY (`falEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`alineacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`alineacion` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`alineacion` (
  `aliId` BIGINT NOT NULL AUTO_INCREMENT,
  `aliJugadorId` BIGINT NULL,
  `aliPosicion` VARCHAR(45) NULL,
  `aliPartidoId` BIGINT NULL,
  `aliEquipoId` BIGINT NULL,
  PRIMARY KEY (`aliId`),
  INDEX `ALINEACION incluye JUGADOR_idx` (`aliJugadorId` ASC) VISIBLE,
  INDEX `ALINEACION agregado PARTIDO_idx` (`aliPartidoId` ASC) INVISIBLE,
  INDEX `ALINEACION incluye EQUIPO_idx` (`aliEquipoId` ASC) VISIBLE,
  CONSTRAINT `ALINEACION incluye JUGADOR`
    FOREIGN KEY (`aliJugadorId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `ALINEACION agregado PARTIDO`
    FOREIGN KEY (`aliPartidoId`)
    REFERENCES `gd-cip`.`partido` (`parId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `ALINEACION incluye EQUIPO`
    FOREIGN KEY (`aliEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`sustitucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`sustitucion` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`sustitucion` (
  `susId` BIGINT NOT NULL AUTO_INCREMENT,
  `susJugadorEntraId` BIGINT NULL,
  `susJugadorSaleId` BIGINT NULL,
  `susDescripcion` VARCHAR(45) NULL,
  `susTiempo` INT NULL,
  `susMinuto` INT NULL,
  `susSegundo` INT NULL,
  `susPartidoId` BIGINT NULL,
  `susEquipoId` BIGINT NULL,
  PRIMARY KEY (`susId`),
  INDEX `GOL incluye JUGADOR_idx` (`susJugadorEntraId` ASC) VISIBLE,
  INDEX `SUSTITUCION agregado PARTIDO_idx` (`susPartidoId` ASC) VISIBLE,
  INDEX `SUSTITUCION incluye EQUIPO_idx` (`susEquipoId` ASC) VISIBLE,
  INDEX `SUSTITUCION incluye JUGADOR 2_idx` (`susJugadorSaleId` ASC) VISIBLE,
  CONSTRAINT `SUSTITUCION incluye JUGADOR 1`
    FOREIGN KEY (`susJugadorEntraId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `SUSTITUCION agregado PARTIDO`
    FOREIGN KEY (`susPartidoId`)
    REFERENCES `gd-cip`.`partido` (`parId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `SUSTITUCION incluye EQUIPO`
    FOREIGN KEY (`susEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `SUSTITUCION incluye JUGADOR 2`
    FOREIGN KEY (`susJugadorSaleId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`portero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`portero` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`portero` (
  `porId` BIGINT NOT NULL AUTO_INCREMENT,
  `porJugadorId` BIGINT NULL,
  `porGoles` INT NULL,
  `porPartidoId` BIGINT NULL,
  `porEquipoId` BIGINT NULL,
  PRIMARY KEY (`porId`),
  INDEX `PORTERO incluye JUGADOR_idx` (`porJugadorId` ASC) VISIBLE,
  INDEX `PORTERO agregado PARTIDO_idx` (`porPartidoId` ASC) VISIBLE,
  INDEX `PORTERO inluye EQUIPO_idx` (`porEquipoId` ASC) VISIBLE,
  CONSTRAINT `PORTERO incluye JUGADOR`
    FOREIGN KEY (`porJugadorId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `PORTERO agregado PARTIDO`
    FOREIGN KEY (`porPartidoId`)
    REFERENCES `gd-cip`.`partido` (`parId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `PORTERO inluye EQUIPO`
    FOREIGN KEY (`porEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`jugada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`jugada` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`jugada` (
  `jugaId` BIGINT NOT NULL AUTO_INCREMENT,
  `jugaJugadorId` BIGINT NULL,
  `jugaDescripcion` VARCHAR(45) NULL,
  `jugaTiempo` INT NULL,
  `jugaMinuto` INT NULL,
  `jugaSegundo` INT NULL,
  `jugaPartidoId` BIGINT NULL,
  `jugaEquipoId` BIGINT NULL,
  PRIMARY KEY (`jugaId`),
  INDEX `GOL incluye JUGADOR_idx` (`jugaJugadorId` ASC) VISIBLE,
  INDEX `JUGADA incluido PARTIDO_idx` (`jugaPartidoId` ASC) VISIBLE,
  INDEX `JUGADA unclute EQUIPO_idx` (`jugaEquipoId` ASC) VISIBLE,
  CONSTRAINT `GOL incluye JUGADOR0`
    FOREIGN KEY (`jugaJugadorId`)
    REFERENCES `gd-cip`.`jugador` (`jugId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `JUGADA incluido PARTIDO`
    FOREIGN KEY (`jugaPartidoId`)
    REFERENCES `gd-cip`.`partido` (`parId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `JUGADA unclute EQUIPO`
    FOREIGN KEY (`jugaEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`clasificacion_cab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`clasificacion_cab` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`clasificacion_cab` (
  `claCabId` BIGINT NOT NULL AUTO_INCREMENT,
  `claCabGrupoId` BIGINT NULL,
  PRIMARY KEY (`claCabId`),
  INDEX `CLASIFICACION_CAB pertenece GRUPO_idx` (`claCabGrupoId` ASC) VISIBLE,
  CONSTRAINT `CLASIFICACION_CAB pertenece GRUPO`
    FOREIGN KEY (`claCabGrupoId`)
    REFERENCES `gd-cip`.`grupo` (`gruId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`clasificacion_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`clasificacion_det` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`clasificacion_det` (
  `claDetId` BIGINT NOT NULL AUTO_INCREMENT,
  `claDetPuntos` INT NULL,
  `claDetJuegos` INT NULL,
  `claDetGanados` INT NULL,
  `claDetEmpates` INT NULL,
  `claDetPerdidos` INT NULL,
  `claDetGolesFavor` INT NULL,
  `claDetGolesContra` INT NULL,
  `claDetDiferenciaPuntos` INT NULL,
  `claDetAprovechamiento` INT NULL,
  `claDetPuntosExtra` INT NULL,
  `claDetEquipoId` BIGINT NULL,
  `claDetCabeceraId` BIGINT NULL,
  PRIMARY KEY (`claDetId`),
  INDEX `CLASIFICACION_DET incluye EQUIPO_idx` (`claDetEquipoId` ASC) VISIBLE,
  INDEX `CLASIFICACION_DET pertenece CLASIFICACION_CAB_idx` (`claDetCabeceraId` ASC) VISIBLE,
  CONSTRAINT `CLASIFICACION_DET incluye EQUIPO`
    FOREIGN KEY (`claDetEquipoId`)
    REFERENCES `gd-cip`.`equipo` (`equId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `CLASIFICACION_DET pertenece CLASIFICACION_CAB`
    FOREIGN KEY (`claDetCabeceraId`)
    REFERENCES `gd-cip`.`clasificacion_cab` (`claCabId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`deporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`deporte` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`deporte` (
  `depId` BIGINT NOT NULL AUTO_INCREMENT,
  `depNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`depId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`tipo_campeonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`tipo_campeonato` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`tipo_campeonato` (
  `idTc` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`idTc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`campeonato_`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`campeonato_` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`campeonato_` (
  `camId` BIGINT NOT NULL AUTO_INCREMENT,
  `camTitulo` VARCHAR(150) NULL DEFAULT NULL,
  `tipo_campeonato_idTC` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`camId`),
  INDEX `CAMPEONATO_ incluye TIPO_CAMPEONATO_idx` (`tipo_campeonato_idTC` ASC) VISIBLE,
  CONSTRAINT `CAMPEONATO_ incluye TIPO_CAMPEONATO`
    FOREIGN KEY (`tipo_campeonato_idTC`)
    REFERENCES `gd-cip`.`tipo_campeonato` (`idTc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gd-cip`.`categorias_`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gd-cip`.`categorias_` ;

CREATE TABLE IF NOT EXISTS `gd-cip`.`categorias_` (
  `idCat` BIGINT NOT NULL AUTO_INCREMENT,
  `catNombre` VARCHAR(150) NULL DEFAULT NULL,
  `campeonato_idCamp` BIGINT NULL DEFAULT NULL,
  `deporte_iddeporte` BIGINT NULL DEFAULT NULL,
  `fases_idfases` BIGINT NULL DEFAULT NULL,
  INDEX `CATEGORIAS_ incluye CAMPEONATO__idx` (`campeonato_idCamp` ASC) VISIBLE,
  INDEX `CATEGORIAS_ incluye DEPORTE_idx` (`deporte_iddeporte` ASC) VISIBLE,
  INDEX `CATEGORIAS_ incluye FASES_idx` (`fases_idfases` ASC) VISIBLE,
  PRIMARY KEY (`idCat`),
  CONSTRAINT `CATEGORIAS_ incluye CAMPEONATO_`
    FOREIGN KEY (`campeonato_idCamp`)
    REFERENCES `gd-cip`.`campeonato_` (`camId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CATEGORIAS_ incluye DEPORTE`
    FOREIGN KEY (`deporte_iddeporte`)
    REFERENCES `gd-cip`.`deporte` (`depId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CATEGORIAS_ incluye FASES`
    FOREIGN KEY (`fases_idfases`)
    REFERENCES `gd-cip`.`fases` (`idfases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gd-cip`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`usuario` (`usuId`, `usuContraseña`, `usuEmail`, `usuNombre`) VALUES (1, 'fdelgadov', 'fdelgadov@unsa.edu.pe', 'Franco Andre Delgado Valencia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`campeonato_unico`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`campeonato_unico` (`camUniId`, `camUniCamId`, `camUniTitulo`, `camUniDescripcion`, `camUniFechaInicio`, `camUniFechaFin`, `camUniTelefono1`, `camUniTelefono2`, `camUniEmail`, `camUniReglas`, `camUniPremio1`, `camUniPremio2`, `camUniPremio3`, `camUniPremioOtro`, `camUniArbId`, `camUniOrganizadorNombre`, `camUniOrganizadorEmail`, `camUniOrganizadorNumero`) VALUES (1, NULL, 'Campeonato 1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `gd-cip`.`campeonato_unico` (`camUniId`, `camUniCamId`, `camUniTitulo`, `camUniDescripcion`, `camUniFechaInicio`, `camUniFechaFin`, `camUniTelefono1`, `camUniTelefono2`, `camUniEmail`, `camUniReglas`, `camUniPremio1`, `camUniPremio2`, `camUniPremio3`, `camUniPremioOtro`, `camUniArbId`, `camUniOrganizadorNombre`, `camUniOrganizadorEmail`, `camUniOrganizadorNumero`) VALUES (2, NULL, 'Campeonato 2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`grupo`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`grupo` (`gruId`, `gruCamUniId`, `gruNombre`) VALUES (1, 1, 'Grupo A');
INSERT INTO `gd-cip`.`grupo` (`gruId`, `gruCamUniId`, `gruNombre`) VALUES (2, 2, 'Grupo B');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`equipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`equipo` (`equId`, `equEmail`, `equNombre`, `equEntrenador`, `equGruId`, `equCampeonatoId`) VALUES (1, 'fdelgadov@unsa.edu.pe', 'Tigres', NULL, NULL, 1);
INSERT INTO `gd-cip`.`equipo` (`equId`, `equEmail`, `equNombre`, `equEntrenador`, `equGruId`, `equCampeonatoId`) VALUES (3, 'fdelgadov@unsa.edu.pe', 'Caballos', NULL, NULL, 1);
INSERT INTO `gd-cip`.`equipo` (`equId`, `equEmail`, `equNombre`, `equEntrenador`, `equGruId`, `equCampeonatoId`) VALUES (2, 'fdelgadov@unsa.edu.pe', 'Leones', NULL, NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`jugador`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`jugador` (`jugId`, `jugEmail`, `jugNombre`, `jugApodo`, `jugPosicion`, `jugDNI`, `jugTelefono`, `jugNacimiento`, `jugCreacion`, `jugEquipoId`) VALUES (1, 'fdelgadov@unsa.edu.pe', 'A', 'A', 'Defensa', '11111111', '333333333', '12/14/11', NULL, 1);
INSERT INTO `gd-cip`.`jugador` (`jugId`, `jugEmail`, `jugNombre`, `jugApodo`, `jugPosicion`, `jugDNI`, `jugTelefono`, `jugNacimiento`, `jugCreacion`, `jugEquipoId`) VALUES (2, 'fdelgadov@unsa.edu.pe', 'B', 'B', 'Defensa', '22222222', '123123123', '25/11/13', NULL, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`usuario_cip`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`usuario_cip` (`usuCipCIP`, `usuCipNombre`) VALUES ('75275880', 'Franco Andre Delgado Valencia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`fases`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`fases` (`idfases`, `nombre`) VALUES (1, 'Todos contra todos');
INSERT INTO `gd-cip`.`fases` (`idfases`, `nombre`) VALUES (2, 'Todos contra todos + Eliminatorias');
INSERT INTO `gd-cip`.`fases` (`idfases`, `nombre`) VALUES (3, 'Eliminatorias');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`fase`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`fase` (`fasId`, `fasTipoFase`, `fasNombre`) VALUES (1, 1, 'Fase 1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`equipo_jugador`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`equipo_jugador` (`equJugJugId`, `equJugEquId`) VALUES (1, 1);
INSERT INTO `gd-cip`.`equipo_jugador` (`equJugJugId`, `equJugEquId`) VALUES (2, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`partido`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`partido` (`parId`, `parFaseId`, `parEquipoId1`, `parEquipoId2`, `parFecha`, `parTipoResultado`, `parMarcador1`, `parMarcador2`, `parMejorJugadorId`) VALUES (1, 1, 1, 2, '01/01/01', 'NO REALIZADO', 2, 1, 1);
INSERT INTO `gd-cip`.`partido` (`parId`, `parFaseId`, `parEquipoId1`, `parEquipoId2`, `parFecha`, `parTipoResultado`, `parMarcador1`, `parMarcador2`, `parMejorJugadorId`) VALUES (2, 1, 2, 1, '01/01/01', 'REALIZADO', 2, 2, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`gol`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`gol` (`golId`, `golJugadorId`, `golAsistenciaId`, `golDescripcion`, `golTiempo`, `golMinuto`, `golSegundo`, `golEnContra`, `golPartidoId`, `golEquipoId`) VALUES (1, 1, 2, NULL, NULL, NULL, NULL, 0, 1, 1);
INSERT INTO `gd-cip`.`gol` (`golId`, `golJugadorId`, `golAsistenciaId`, `golDescripcion`, `golTiempo`, `golMinuto`, `golSegundo`, `golEnContra`, `golPartidoId`, `golEquipoId`) VALUES (2, 2, 1, NULL, NULL, NULL, NULL, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`color`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`color` (`colId`, `colNombre`) VALUES (1, 'Amarilla');
INSERT INTO `gd-cip`.`color` (`colId`, `colNombre`) VALUES (2, 'Roja');
INSERT INTO `gd-cip`.`color` (`colId`, `colNombre`) VALUES (3, 'Azul');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`tarjeta`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`tarjeta` (`tarId`, `tarJugadorId`, `tarTiempo`, `tarMinuto`, `tarSegundo`, `tarDescripcion`, `tarColorId`, `tarPartidoId`, `tarEquipoId`) VALUES (1, 1, NULL, NULL, NULL, NULL, 1, 1, 1);
INSERT INTO `gd-cip`.`tarjeta` (`tarId`, `tarJugadorId`, `tarTiempo`, `tarMinuto`, `tarSegundo`, `tarDescripcion`, `tarColorId`, `tarPartidoId`, `tarEquipoId`) VALUES (2, 2, NULL, NULL, NULL, NULL, 2, 1, 1);
INSERT INTO `gd-cip`.`tarjeta` (`tarId`, `tarJugadorId`, `tarTiempo`, `tarMinuto`, `tarSegundo`, `tarDescripcion`, `tarColorId`, `tarPartidoId`, `tarEquipoId`) VALUES (3, 1, NULL, NULL, NULL, NULL, 3, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`falta`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`falta` (`falId`, `falJugadorId`, `falTiempo`, `falMinuto`, `falSegundo`, `falPartidoId`, `falEquipoId`) VALUES (1, 1, NULL, NULL, NULL, 1, 1);
INSERT INTO `gd-cip`.`falta` (`falId`, `falJugadorId`, `falTiempo`, `falMinuto`, `falSegundo`, `falPartidoId`, `falEquipoId`) VALUES (2, 2, NULL, NULL, NULL, 1, 1);
INSERT INTO `gd-cip`.`falta` (`falId`, `falJugadorId`, `falTiempo`, `falMinuto`, `falSegundo`, `falPartidoId`, `falEquipoId`) VALUES (3, 1, NULL, NULL, NULL, 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`alineacion`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`alineacion` (`aliId`, `aliJugadorId`, `aliPosicion`, `aliPartidoId`, `aliEquipoId`) VALUES (1, 1, 'Portero', 1, 1);
INSERT INTO `gd-cip`.`alineacion` (`aliId`, `aliJugadorId`, `aliPosicion`, `aliPartidoId`, `aliEquipoId`) VALUES (2, 2, 'Defensa', 1, 1);
INSERT INTO `gd-cip`.`alineacion` (`aliId`, `aliJugadorId`, `aliPosicion`, `aliPartidoId`, `aliEquipoId`) VALUES (3, 1, 'Delantero', 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`sustitucion`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`sustitucion` (`susId`, `susJugadorEntraId`, `susJugadorSaleId`, `susDescripcion`, `susTiempo`, `susMinuto`, `susSegundo`, `susPartidoId`, `susEquipoId`) VALUES (1, 1, 2, NULL, NULL, NULL, NULL, 1, 1);
INSERT INTO `gd-cip`.`sustitucion` (`susId`, `susJugadorEntraId`, `susJugadorSaleId`, `susDescripcion`, `susTiempo`, `susMinuto`, `susSegundo`, `susPartidoId`, `susEquipoId`) VALUES (2, 2, 1, NULL, NULL, NULL, NULL, 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`portero`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`portero` (`porId`, `porJugadorId`, `porGoles`, `porPartidoId`, `porEquipoId`) VALUES (1, 1, 1, 1, 1);
INSERT INTO `gd-cip`.`portero` (`porId`, `porJugadorId`, `porGoles`, `porPartidoId`, `porEquipoId`) VALUES (2, 2, 2, 1, 1);
INSERT INTO `gd-cip`.`portero` (`porId`, `porJugadorId`, `porGoles`, `porPartidoId`, `porEquipoId`) VALUES (3, 1, 3, 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`jugada`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`jugada` (`jugaId`, `jugaJugadorId`, `jugaDescripcion`, `jugaTiempo`, `jugaMinuto`, `jugaSegundo`, `jugaPartidoId`, `jugaEquipoId`) VALUES (1, 1, '111', NULL, NULL, NULL, 1, 1);
INSERT INTO `gd-cip`.`jugada` (`jugaId`, `jugaJugadorId`, `jugaDescripcion`, `jugaTiempo`, `jugaMinuto`, `jugaSegundo`, `jugaPartidoId`, `jugaEquipoId`) VALUES (2, 2, '222', NULL, NULL, NULL, 1, 1);
INSERT INTO `gd-cip`.`jugada` (`jugaId`, `jugaJugadorId`, `jugaDescripcion`, `jugaTiempo`, `jugaMinuto`, `jugaSegundo`, `jugaPartidoId`, `jugaEquipoId`) VALUES (3, 1, '333', NULL, NULL, NULL, 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`clasificacion_cab`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`clasificacion_cab` (`claCabId`, `claCabGrupoId`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`clasificacion_det`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`clasificacion_det` (`claDetId`, `claDetPuntos`, `claDetJuegos`, `claDetGanados`, `claDetEmpates`, `claDetPerdidos`, `claDetGolesFavor`, `claDetGolesContra`, `claDetDiferenciaPuntos`, `claDetAprovechamiento`, `claDetPuntosExtra`, `claDetEquipoId`, `claDetCabeceraId`) VALUES (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO `gd-cip`.`clasificacion_det` (`claDetId`, `claDetPuntos`, `claDetJuegos`, `claDetGanados`, `claDetEmpates`, `claDetPerdidos`, `claDetGolesFavor`, `claDetGolesContra`, `claDetDiferenciaPuntos`, `claDetAprovechamiento`, `claDetPuntosExtra`, `claDetEquipoId`, `claDetCabeceraId`) VALUES (2, 2, 2, 3, 2, 2, 2, 2, 5, 2, 2, 2, 1);
INSERT INTO `gd-cip`.`clasificacion_det` (`claDetId`, `claDetPuntos`, `claDetJuegos`, `claDetGanados`, `claDetEmpates`, `claDetPerdidos`, `claDetGolesFavor`, `claDetGolesContra`, `claDetDiferenciaPuntos`, `claDetAprovechamiento`, `claDetPuntosExtra`, `claDetEquipoId`, `claDetCabeceraId`) VALUES (3, 1, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 1);
INSERT INTO `gd-cip`.`clasificacion_det` (`claDetId`, `claDetPuntos`, `claDetJuegos`, `claDetGanados`, `claDetEmpates`, `claDetPerdidos`, `claDetGolesFavor`, `claDetGolesContra`, `claDetDiferenciaPuntos`, `claDetAprovechamiento`, `claDetPuntosExtra`, `claDetEquipoId`, `claDetCabeceraId`) VALUES (4, 2, 4, 4, 5, 4, 4, 4, 6, 4, 4, 1, 1);
INSERT INTO `gd-cip`.`clasificacion_det` (`claDetId`, `claDetPuntos`, `claDetJuegos`, `claDetGanados`, `claDetEmpates`, `claDetPerdidos`, `claDetGolesFavor`, `claDetGolesContra`, `claDetDiferenciaPuntos`, `claDetAprovechamiento`, `claDetPuntosExtra`, `claDetEquipoId`, `claDetCabeceraId`) VALUES (5, 1, 4, 1, 7, 3, 4, 4, 3, 5, 5, 2, 1);
INSERT INTO `gd-cip`.`clasificacion_det` (`claDetId`, `claDetPuntos`, `claDetJuegos`, `claDetGanados`, `claDetEmpates`, `claDetPerdidos`, `claDetGolesFavor`, `claDetGolesContra`, `claDetDiferenciaPuntos`, `claDetAprovechamiento`, `claDetPuntosExtra`, `claDetEquipoId`, `claDetCabeceraId`) VALUES (6, 2, 6, 3, 4, 2, 3, 2, 7, 6, 6, 3, 1);
INSERT INTO `gd-cip`.`clasificacion_det` (`claDetId`, `claDetPuntos`, `claDetJuegos`, `claDetGanados`, `claDetEmpates`, `claDetPerdidos`, `claDetGolesFavor`, `claDetGolesContra`, `claDetDiferenciaPuntos`, `claDetAprovechamiento`, `claDetPuntosExtra`, `claDetEquipoId`, `claDetCabeceraId`) VALUES (7, 1, 2, 2, 3, 1, 1, 3, 4, 7, 7, 1, 1);
INSERT INTO `gd-cip`.`clasificacion_det` (`claDetId`, `claDetPuntos`, `claDetJuegos`, `claDetGanados`, `claDetEmpates`, `claDetPerdidos`, `claDetGolesFavor`, `claDetGolesContra`, `claDetDiferenciaPuntos`, `claDetAprovechamiento`, `claDetPuntosExtra`, `claDetEquipoId`, `claDetCabeceraId`) VALUES (8, 2, 5, 4, 1, 2, 2, 4, 8, 8, 8, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`deporte`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`deporte` (`depId`, `depNombre`) VALUES (1, 'Fútbol');
INSERT INTO `gd-cip`.`deporte` (`depId`, `depNombre`) VALUES (2, 'Voley');
INSERT INTO `gd-cip`.`deporte` (`depId`, `depNombre`) VALUES (3, 'Baloncesto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gd-cip`.`tipo_campeonato`
-- -----------------------------------------------------
START TRANSACTION;
USE `gd-cip`;
INSERT INTO `gd-cip`.`tipo_campeonato` (`idTc`, `tipo`) VALUES (1, 'Campeonato único');
INSERT INTO `gd-cip`.`tipo_campeonato` (`idTc`, `tipo`) VALUES (2, 'Campeonato con Categorías');

COMMIT;

